// Generated by ts-to-zod
import { z } from "zod";

const parse_domain_validation_error_zods = z.object({
    type: z.string(),
    message: z.string(),
    column: z.number()
});

export const urlparsed_domain_result_t_zods = z.object({
    type: z.union([z.literal("INVALID"), z.literal("IP"), z.literal("RESERVED"), z.literal("NOT_LISTED"), z.literal("LISTED")]),
    hostname: z.string(),
    errors: z.array(parse_domain_validation_error_zods),
    labels: z.array(z.string()),
    subdomains: z.array(z.string()),
    domain: z.string(),
    top_level_domains: z.array(z.string()),
    icann: z.object({
        subdomains: z.array(z.string()),
        domain: z.string(),
        top_level_domains: z.array(z.string())
    })
});

export const url_generation_options_t_zods = z.object({
    seed: z.number().optional(),
    complexity_bias: z.number().optional(),
    include_tricky_valid_cases: z.boolean().optional(),
    complexity_weighting_strength: z.number().optional()
});

export const url_diagnostic_issue_t_zods = z.object({
    code: z.string(),
    message: z.string(),
    offset: z.number(),
    length: z.number(),
    found: z.string().optional(),
    expected: z.string().optional(),
    context: z.string().optional(),
    severity: z.union([z.literal("fatal"), z.literal("warning")])
});

export const node_url_error_t_zods = z.object({
    name: z.string(),
    message: z.string(),
    code: z.string().optional()
});

export const url_diagnostic_result_t_zods = z.union([z.object({
        ok: z.literal(true),
        url: z.string(),
        normalized: z.string(),
        issues: z.array(url_diagnostic_issue_t_zods)
    }), z.object({
        ok: z.literal(false),
        issues: z.array(url_diagnostic_issue_t_zods),
        node_error: node_url_error_t_zods.optional()
    })]);

export const parser_context_t_zods = z.object({
    input: z.string(),
    base: z.string().optional(),
    issues: z.array(url_diagnostic_issue_t_zods)
});

export const parsed_components_t_zods = z.object({
    scheme: z.string(),
    has_authority: z.boolean(),
    username: z.string(),
    password: z.string(),
    host: z.string(),
    port: z.string(),
    pathname: z.string(),
    search: z.string(),
    hash: z.string()
});

export const urlparsed_hashes_t_zods = z.object({
    url: z.string()
});

export const urlparsed_analysis_t_zods = z.object({
    has_params: z.boolean()
});

export const urlparse_user_and_password_info_t_zods = z.object({
    username: z.string().nullable(),
    username_lowercase: z.string().nullable(),
    password: z.string().nullable(),
    password_lowercase: z.string().nullable()
});

export const urlparse_port_and_protocol_info_t_zods = z.object({
    scheme: z.string(),
    protocol: z.string(),
    port: z.number(),
    protocol_std_port: z.number()
});

export const urlparse_host_info_t_zods = z.object({
    host: z.string(),
    host_with_protocol: z.string(),
    host_lowercase: z.string(),
    host_with_protocol_lowercase: z.string(),
    domain: z.string().nullable(),
    domain_with_tld: z.string().nullable(),
    domain_with_subdomains_and_tld: z.string().nullable(),
    top_level_domain: z.string().nullable(),
    subdomains: z.string().nullable(),
    host_domain_information_parsed: urlparsed_domain_result_t_zods.nullable()
});

export const urlparse_base_info_t_zods = z.object({
    base: z.string(),
    base_lowercase: z.string(),
    base_without_port: z.string(),
    base_without_port_lowercase: z.string()
});

export const urlparsed_path_charsets_t_zods = z.object({
    idx: z.number(),
    chars: z.array(z.string()),
    chars_lowercase: z.array(z.string()),
    path: z.string()
});

export const url_parsed_path_part_t_zods = z.object({
    part: z.string(),
    length: z.string()
});

export const urlparsed_path_component_t_zods = z.object({
    idx: z.number(),
    content: z.string(),
    length: z.number(),
    char_set: z.array(z.string())
});

export const urlparsed_path_element_details_t_zods = z.object({
    idx: z.number(),
    path_elem: z.string(),
    length: z.number(),
    numeric: z.array(urlparsed_path_component_t_zods),
    numeric_unique: z.array(urlparsed_path_component_t_zods),
    non_numeric: z.array(urlparsed_path_component_t_zods),
    non_numeric_unique: z.array(urlparsed_path_component_t_zods),
    non_alpha_non_numeric: z.array(urlparsed_path_component_t_zods),
    alphabetic: z.array(urlparsed_path_component_t_zods),
    alphabetic_unique: z.array(urlparsed_path_component_t_zods),
    nonalphanumeric: z.array(urlparsed_path_component_t_zods),
    nonalphanumeric_unique: z.array(urlparsed_path_component_t_zods)
});

export const urlparsed_resource_details_t_zods = z.object({
    resource: z.string().nullable(),
    name: z.string().nullable(),
    extension: z.string().nullable(),
    parts: z.array(z.string()),
    is_hidden_file: z.boolean(),
    resource_unique_chars: z.array(z.string())
});

export const urlparsed_path_t_zods = z.object({
    path: z.array(z.string()),
    path_sorted: z.array(z.string()),
    path_str: z.string().nullable(),
    path_str_unique_chars: z.array(z.string()),
    resource: z.string().nullable(),
    resource_details: urlparsed_resource_details_t_zods,
    resource_details_lowercase: urlparsed_resource_details_t_zods,
    path_elem_details: z.array(urlparsed_path_element_details_t_zods)
});

export const urlparsed_path_and_resource_info_t_zods = z.object({
    resource_str: z.string().nullable(),
    resource_str_lowercase: z.string().nullable(),
    resource_str_length: z.number(),
    pathname: z.string(),
    pathname_lowercase: z.string(),
    pathname_normalized: z.string(),
    pathname_normalized_lowercase: z.string(),
    pathname_length: z.number(),
    path_parsed: urlparsed_path_t_zods.nullable(),
    path_parsed_collapsed: urlparsed_path_t_zods.nullable(),
    path_parsed_collapsed_lowercase: urlparsed_path_t_zods.nullable()
});

export const urlparsed_path_numeric_components_t_zods = z.array(z.number());

export const urlparsed_indicators_t_zods = z.object({
    failures: z.object({
        failed_basic_parsing: z.boolean().optional(),
        port_is_missing: z.boolean().optional()
    }),
    has_failures: z.boolean().optional(),
    has_url_base: z.boolean().optional(),
    has_embedded_port: z.boolean().optional(),
    has_embedded_username: z.boolean().optional(),
    has_embedded_password: z.boolean().optional(),
    is_not_http_or_https: z.boolean().optional(),
    is_http: z.boolean().optional(),
    is_https: z.boolean().optional(),
    is_websocket: z.boolean().optional(),
    is_ipv4_address: z.boolean().optional(),
    is_ipv6_address: z.boolean().optional(),
    has_nonstandard_protocol_port: z.boolean().optional(),
    has_url_parameters: z.boolean().optional(),
    has_paths: z.boolean().optional(),
    has_numeric_path: z.boolean().optional(),
    has_numeric_parameters: z.boolean().optional(),
    has_numeric_parameter_names: z.boolean().optional(),
    has_resource_filename_extension: z.boolean().optional(),
    is_protocol_standard_port: z.boolean().optional(),
    has_invalid_tcp_port: z.boolean().optional()
});

export const urlparsed_queryparam_t_zods = z.object({
    idx: z.number(),
    key: z.string().nullable(),
    key_alphabetics: z.array(z.string()).nullable(),
    key_nonalphanumerics: z.array(z.string()).nullable(),
    key_nonnumerics: z.array(z.string()).nullable(),
    key_numerics: z.array(z.string()).nullable(),
    key_unique_chars: z.array(z.string()).nullable(),
    key_lowercase: z.string().nullable(),
    key_lowercase_alphabetics: z.array(z.string()).nullable(),
    key_lowercase_nonalphanumerics: z.array(z.string()).nullable(),
    key_lowercase_nonnumerics: z.array(z.string()).nullable(),
    key_lowercase_numerics: z.array(z.string()).nullable(),
    key_lowercase_unique_chars: z.array(z.string()).nullable(),
    val: z.string().nullable(),
    val_alphabetics: z.array(z.string()).nullable(),
    val_nonalphanumerics: z.array(z.string()).nullable(),
    val_nonnumerics: z.array(z.string()).nullable(),
    val_numerics: z.array(z.string()).nullable(),
    val_unique_chars: z.array(z.string()).nullable(),
    val_lowercase: z.string().nullable(),
    val_lowercase_alphabetics: z.array(z.string()).nullable(),
    val_lowercase_nonalphanumerics: z.array(z.string()).nullable(),
    val_lowercase_nonnumerics: z.array(z.string()).nullable(),
    val_lowercase_numerics: z.array(z.string()).nullable(),
    val_lowercase_unique_chars: z.array(z.string()).nullable()
});

export const urlparsed_param_info_t_zods = z.object({
    param_str: z.string(),
    param_str_lowercase: z.string(),
    params_as_array: z.array(urlparsed_queryparam_t_zods)
});

export const url_hash_data_t_zods = z.object({
    hash: z.string().nullable(),
    hash_lowercase: z.string().nullable()
});

export const unusual_url_type_t_zods = z.union([z.literal("unknown_type"), z.literal("data_url_type"), z.literal("blob_url_type"), z.literal("about_url_type"), z.literal("mailto_url_type"), z.literal("telephone_url_type"), z.literal("urn_url_type"), z.literal("unknown_type")]);

export const data_url_info_t_zods = z.object({
    scheme: z.literal("data"),
    media_type: z.string(),
    charset: z.string().nullable(),
    is_base64: z.boolean(),
    data: z.string(),
    metadata: z.string()
});

export const blob_url_info_t_zods = z.object({
    scheme: z.literal("blob"),
    origin: z.string(),
    uuid: z.string(),
    query: z.string().nullable(),
    fragment: z.string().nullable(),
    raw: z.string()
});

export const about_url_info_t_zods = z.object({
    scheme: z.literal("about"),
    identifier: z.string(),
    query: z.string().nullable(),
    fragment: z.string().nullable(),
    raw: z.string()
});

export const mailto_url_info_t_zods = z.object({
    scheme: z.literal("mailto"),
    raw: z.string(),
    to: z.array(z.string()),
    cc: z.array(z.string()),
    bcc: z.array(z.string()),
    subject: z.array(z.string()),
    body: z.array(z.string()),
    other_query_params: z.record(z.string(), z.array(z.string())),
    fragment: z.string().nullable()
});

export const tel_url_info_t_zods = z.object({
    scheme: z.literal("tel"),
    phone_number: z.string(),
    parameters: z.record(z.string(), z.array(z.string())),
    raw: z.string()
});

export const urn_url_info_t_zods = z.object({
    scheme: z.literal("urn"),
    nid: z.string(),
    nss: z.string(),
    query: z.string().nullable(),
    fragment: z.string().nullable(),
    raw: z.string()
});

export const urlparsed_t_zods = z.object({
    type: z.union([z.literal("websocket"), z.literal("web"), z.literal("email"), z.literal("service"), z.literal("data"), z.literal("blob"), z.literal("about"), z.literal("mailto"), z.literal("telephone"), z.literal("urn"), z.literal("other"), z.literal("unset")]),
    parsed_ok: z.boolean(),
    data_url_info: data_url_info_t_zods.optional().nullable(),
    blob_url_info: blob_url_info_t_zods.optional().nullable(),
    about_url_info: about_url_info_t_zods.optional().nullable(),
    mailto_url_info: mailto_url_info_t_zods.optional().nullable(),
    tel_url_info: tel_url_info_t_zods.optional().nullable(),
    urn_url_info: urn_url_info_t_zods.optional().nullable(),
    scheme_and_port_info: urlparse_port_and_protocol_info_t_zods.optional().nullable(),
    user_and_password_info: urlparse_user_and_password_info_t_zods.optional().nullable(),
    host_info: urlparse_host_info_t_zods.optional().nullable(),
    base_info: urlparse_base_info_t_zods.optional().nullable(),
    path_and_resource_info: urlparsed_path_and_resource_info_t_zods.optional().nullable(),
    parameter_info: urlparsed_param_info_t_zods.optional().nullable(),
    hash_info: url_hash_data_t_zods.optional().nullable(),
    failed_parse_diagnostics: url_diagnostic_result_t_zods.optional().nullable(),
    indicators: z.any().optional()
});
