// Generated by ts-to-zod
import { z } from "zod";

export const parsed_domain_info_t_zods = z.unknown();

export const url_diagnostic_issue_t_zods = z.object({
    code: z.string(),
    message: z.string(),
    offset: z.number(),
    length: z.number(),
    found: z.string().optional(),
    expected: z.string().optional(),
    context: z.string().optional(),
    severity: z.union([z.literal("fatal"), z.literal("warning")])
});

export const node_url_error_t_zods = z.object({
    name: z.string(),
    message: z.string(),
    code: z.string().optional()
});

export const url_diagnostic_result_t_zods = z.union([z.object({
        ok: z.literal(true),
        url: z.string(),
        normalized: z.string(),
        issues: z.array(url_diagnostic_issue_t_zods)
    }), z.object({
        ok: z.literal(false),
        issues: z.array(url_diagnostic_issue_t_zods),
        node_error: node_url_error_t_zods.optional()
    })]);

export const parser_context_t_zods = z.object({
    input: z.string(),
    base: z.string().optional(),
    issues: z.array(url_diagnostic_issue_t_zods)
});

export const parsed_components_t_zods = z.object({
    scheme: z.string(),
    has_authority: z.boolean(),
    username: z.string(),
    password: z.string(),
    host: z.string(),
    port: z.string(),
    pathname: z.string(),
    search: z.string(),
    hash: z.string()
});

export const urlparsed_hashes_t_zods = z.object({
    url: z.string()
});

export const urlparsed_analysis_t_zods = z.object({
    has_params: z.boolean()
});

export const urlparse_user_and_password_info_t_zods = z.object({
    username: z.string().nullable(),
    username_lowercase: z.string().nullable(),
    password: z.string().nullable(),
    password_lowercase: z.string().nullable()
});

export const urlparse_port_and_protocol_info_t_zods = z.object({
    scheme: z.string(),
    protocol: z.string(),
    port: z.number(),
    protocol_std_port: z.number()
});

export const urlparse_host_info_t_zods = z.object({
    host: z.string(),
    host_with_protocol: z.string(),
    host_lowercase: z.string(),
    host_with_protocol_lowercase: z.string(),
    host_domain_information_parsed: parsed_domain_info_t_zods.nullable()
});

export const urlparse_base_info_t_zods = z.object({
    base: z.string(),
    base_lowercase: z.string(),
    base_without_port: z.string(),
    base_without_port_lowercase: z.string()
});

export const urlparsed_baseinfo_t_zods = z.object({
    base: z.string(),
    base_with_port: z.string()
});

export const urlparsed_resource_t_zods = z.object({
    name: z.string().nullable(),
    extension: z.string().nullable()
});

export const urlparsed_path_t_zods = z.object({
    path: z.array(z.string()),
    path_sorted: z.array(z.string()),
    path_str: z.string().nullable(),
    resource: z.string().nullable()
});

export const urlparsed_path_numeric_components_t_zods = z.array(z.number());

export const urlparsed_indicators_t_zods = z.object({
    failures: z.object({
        failed_basic_parsing: z.boolean().optional(),
        port_is_missing: z.boolean().optional()
    }),
    has_failures: z.boolean().optional(),
    has_url_base: z.boolean().optional(),
    has_embedded_port: z.boolean().optional(),
    has_embedded_username: z.boolean().optional(),
    has_embedded_password: z.boolean().optional(),
    is_not_http_or_https: z.boolean().optional(),
    is_http: z.boolean().optional(),
    is_https: z.boolean().optional(),
    is_websocket: z.boolean().optional(),
    is_ipv4_address: z.boolean().optional(),
    is_ipv6_address: z.boolean().optional(),
    has_nonstandard_protocol_port: z.boolean().optional(),
    has_url_parameters: z.boolean().optional(),
    has_paths: z.boolean().optional(),
    has_numeric_path: z.boolean().optional(),
    has_numeric_parameters: z.boolean().optional(),
    has_numeric_parameter_names: z.boolean().optional(),
    has_script_filename_extension: z.boolean().optional(),
    is_protocol_standard_port: z.boolean().optional(),
    has_invalid_tcp_port: z.boolean().optional()
});

export const urlparse_fail_indicators_t_zods = z.object({
    url_failed_basic_parse: z.boolean()
});

export const urlparsed_queryparam_t_zods = z.object({
    key: z.string().nullable(),
    val: z.string().nullable()
});

export const urlparsed_param_info_t_zods = z.object({
    param_str: z.string(),
    param_str_lowercase: z.string(),
    params_as_array: z.array(urlparsed_queryparam_t_zods),
    params_as_array_lowercase: z.array(urlparsed_queryparam_t_zods)
});

export const urlparsed_path_and_resource_info_t_zods = z.object({
    resource_str: z.string().nullable(),
    resource_str_lowercase: z.string().nullable(),
    resource_info: urlparsed_resource_t_zods,
    resource_info_lowercase: urlparsed_resource_t_zods,
    pathname: z.string(),
    pathname_lowercase: z.string(),
    pathname_normalized: z.string(),
    pathname_normalized_lowercase: z.string(),
    path_parsed: urlparsed_path_t_zods.nullable(),
    path_parsed_collapsed: urlparsed_path_t_zods.nullable(),
    path_parsed_collapsed_lowercase: urlparsed_path_t_zods.nullable(),
    numeric_path_data: z.array(z.string()),
    non_numeric_path_data: z.array(z.string()),
    non_numeric_lowercase_path_data: z.array(z.string()),
    alphabetic_path_data: z.array(z.string()),
    alphabetic_lowercase_path_data: z.array(z.string()),
    numeric_path_data_unique: z.array(z.string()),
    non_numeric_path_data_unique: z.array(z.string()),
    non_numeric_lowercase_path_data_unique: z.array(z.string()),
    alphabetic_path_data_unique: z.array(z.string()),
    alphabetic_lowercase_path_data_unique: z.array(z.string()),
    numeric_path_data_unique_sorted: z.array(z.string()),
    non_numeric_path_data_unique_sorted: z.array(z.string()),
    non_numeric_lowercase_path_data_unique_sorted: z.array(z.string()),
    alphabetic_path_data_unique_sorted: z.array(z.string()),
    alphabetic_lowercase_path_data_unique_sorted: z.array(z.string())
});

export const urlparsed_t_zods = z.object({
    scheme_and_port_info: urlparse_port_and_protocol_info_t_zods.optional().nullable(),
    user_and_password_info: urlparse_user_and_password_info_t_zods.optional().nullable(),
    host_info: urlparse_host_info_t_zods.optional().nullable(),
    base_info: urlparse_base_info_t_zods.optional().nullable(),
    path_and_resource_info: urlparsed_path_and_resource_info_t_zods.optional().nullable(),
    parameter_info: urlparsed_param_info_t_zods.optional().nullable(),
    failed_parse_diagnostics: url_diagnostic_result_t_zods.optional().nullable(),
    indicators: urlparsed_indicators_t_zods
});
